server:
  port: 8081

spring:
  redis:
    host: 192.168.136.128
    port: 6379
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


logging:
  level:
    com: INFO
    #打印出比较详细的事务过程
    org.springframework.jdbc: DEBUG

#云通讯
ytx:
  server: app.cloopen.com
  port: 8883
  accountsid: aaf98f8951eb7f810151f2b16b0a1388
  accounttoken: 751d92e39a4b4d4c841025f7d574569b
  appid: 8aaf070867e8660f0167f968d1500a83