applicationName: mq
server:
  port: 8011

quanroon:
  rocketmq:
    # NameServer地址 用;作为地址的分隔符
    namesrv-addr: 192.168.136.128:9876
    producer:
      # 生产者的组名
      enable: true
      groupName: product-test
    consumer:
      enable: true
      topic: yaoshuangqi-topic
      groupName: consumer-test
      order:
        enable: false
        topic: yaoshuangqi-topic
        group-name: order-consumer-test
